/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      'ichef.bbci.co.uk',
      'image.cnbcfm.com',
      '**.ignimgs.com',
      '**.ign.com',
      '**.gamespot.com',
      '**.polygon.com',
      '**.vg247.com',
      '**.gamesradar.com',
      '**.gamespot.com',
      '**.polygon.com',
      '**.ign.com',
      '**.abcnewsfe.com',
      'www.politico.com',
      'www.gematsu.com',
      '**.nintendolife.com',
      '**.videocardz.com',
      '**.**.com',
      '**.cloudfront.net',
      'nypost.com',
      'gizmodo.com',
      '**.lura.live',
      '**.lemde.fr',
      '**.lesechos.com',
      '**.lemonde.fr',
      '**.lefigaro.fr',
      '**.leparisien.fr',
      '**.lemonde.fr',
      '**.lefigaro.fr',
      '**.leparisien.fr',
      '**.**.fr',
      'media.lesechos.com',
      'img.lemde.fr',
      'www.lemonde.fr',
      'www.lesechos.fr',
      'www.lefigaro.fr',
      'www.liberation.fr',
      'neurosciencenews.com',
      'scitechdaily.com',
      '**.psypost.org',
      'wlos.com',
      'dailygalaxy.com',
      '**.futurecdn.net',
      'nesn.com',
      '**.wsj.net',
      'scx2.b-cdn.net',
    ],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.lesechos.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'scx2.b-cdn.net',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.wsj.net',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.nesn.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.neurosciencenews.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'wlos.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.futurecdn.net',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'dailygalaxy.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.psypost.org',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.scitechdaily.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.lemde.fr',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.**.fr',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.lemonde.fr',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.lefigaro.fr',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.leparisien.fr',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.lura.live',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'gizmodo.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'nypost.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.ignimgs.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.cloudfront.net',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'www.politico.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.**.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.nintendolife.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.videocardz.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'www.gematsu.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.abcnewsfe.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'variety.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.wsj.net',
        port: '',
        pathname: '/im-**',
      },
      {
        protocol: 'https',
        hostname: '**.wsj.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.nyt.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.reuters.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.bloomberg.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.ft.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'static01.nyt.com',
        port: '',
        pathname: '/**',
        },
      {
        protocol: 'https',
        hostname: 'media.cnn.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'cdn.cnn.com',
        port: '',
        pathname: '/**',
        },
      {
        protocol: 'https',
        hostname: 'i.guim.co.uk',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'assets.bwbx.io',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'img.washingtonpost.com',
        port: '',
        pathname: '/**',
      },
      // Gaming and Entertainment domains
      {
        protocol: 'https',
        hostname: 'assets.ignimgs.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.ignimgs.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'media.ignimgs.com',
        port: '',
        pathname: '/**',
        },
      {
        protocol: 'https',
        hostname: '**.ign.com',
        port: '',
        pathname: '/**',
      },
      // Additional gaming news domains
      {
        protocol: 'https',
        hostname: '**.gamespot.com',
        port: '',
        pathname: '/**',
        },
      {
        protocol: 'https',
        hostname: '**.polygon.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'assets.vg247.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '**.gamesradar.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'media.lesechos.com',
        pathname: '/api/v1/images/**',
      },
      {
        protocol: 'https',
        hostname: 'img.lemde.fr',
        pathname: '/**',
      },
    ],
  },
  experimental: {
    images: {
      allowFutureImage: true,
    },
  }
};

module.exports = nextConfig;